"""launchd (Mac) scheduler for gmail-cleanup autopilot."""

from __future__ import annotations

import platform
import subprocess
from pathlib import Path


PLIST_LABEL = 'com.github.bgorzelic.gmail-cleanup'
LAUNCHAGENTS_DIR = Path.home() / 'Library' / 'LaunchAgents'
PLIST_PATH = LAUNCHAGENTS_DIR / f'{PLIST_LABEL}.plist'
WRAPPER_PATH = Path.home() / '.gmail_cli' / 'bin' / 'run-autopilot.sh'
LOG_DIR = Path.home() / '.gmail_cli' / 'logs'


def ensure_mac() -> None:
    if platform.system() != 'Darwin':
        print("❌ Scheduler is Mac-only in v0.5. Linux/Windows planned for v0.6.")
        raise SystemExit(1)


def install(email: str, time_hhmm: str, escalate: bool, force: bool = False) -> None:
    ensure_mac()
    if PLIST_PATH.exists() and not force:
        print(f"❌ Job already at {PLIST_PATH}.")
        print(f"   Use --force or run: gmail-cleanup schedule uninstall")
        raise SystemExit(1)

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    WRAPPER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LAUNCHAGENTS_DIR.mkdir(parents=True, exist_ok=True)

    escalate_flag = '--escalate' if escalate else ''
    bin_path = Path.cwd() / '.venv' / 'bin' / 'gmail-cleanup'
    if not bin_path.exists():
        bin_path = 'gmail-cleanup'
    wrapper = f"""#!/bin/bash
# Generated by gmail-cleanup schedule install.
set -euo pipefail
DATE=$(date +%Y-%m-%d)
LOG="$HOME/.gmail_cli/logs/autopilot-$DATE.log"
export GMAIL_CLEANUP_SCHEDULED=1
exec >>"$LOG" 2>&1
echo "[$(date)] starting autopilot for {email}"
exec {bin_path} --email {email} autopilot {escalate_flag} --quiet
"""
    WRAPPER_PATH.write_text(wrapper)
    WRAPPER_PATH.chmod(0o755)

    hh, mm = time_hhmm.split(':')
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{PLIST_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{WRAPPER_PATH}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>{int(hh)}</integer>
        <key>Minute</key>
        <integer>{int(mm)}</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""
    PLIST_PATH.write_text(plist)

    subprocess.run(['launchctl', 'unload', str(PLIST_PATH)], capture_output=True)
    res = subprocess.run(['launchctl', 'load', str(PLIST_PATH)], capture_output=True, text=True)
    if res.returncode != 0:
        print(f"⚠️  launchctl load failed: {res.stderr}")

    print(f"✅ Scheduled autopilot for {email} at {time_hhmm} daily")
    print(f"   plist:   {PLIST_PATH}")
    print(f"   wrapper: {WRAPPER_PATH}")
    print(f"   logs:    {LOG_DIR}/autopilot-YYYY-MM-DD.log")


def uninstall() -> None:
    ensure_mac()
    if not PLIST_PATH.exists():
        print(f"ℹ️  No scheduled job at {PLIST_PATH}")
        return
    subprocess.run(['launchctl', 'unload', str(PLIST_PATH)], capture_output=True)
    PLIST_PATH.unlink()
    print(f"✅ Scheduled job removed.")


def status() -> None:
    ensure_mac()
    if not PLIST_PATH.exists():
        print(f"ℹ️  No scheduled job. Install with: gmail-cleanup schedule install")
        return
    res = subprocess.run(['launchctl', 'list', PLIST_LABEL], capture_output=True, text=True)
    print(f"📋 Plist:   {PLIST_PATH}")
    print(f"📜 Wrapper: {WRAPPER_PATH}")
    print(f"📁 Logs:    {LOG_DIR}")
    if res.returncode == 0:
        print(f"\n{res.stdout}")
    else:
        print(f"⚠️  launchctl reports the job is not loaded.")
